name: personal_injury_networking
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0' 

dependencies:
  flutter:
    sdk: flutter
 
  cupertino_icons: ^1.0.2
  google_fonts: ^4.0.3
  flutter_screenutil: ^5.6.1
  flutter_rating_stars: ^1.0.3+4
  page_transition: ^2.1.0
  stepper_page_view: ^0.0.2

  # provider: ^6.0.5
  # emoji_picker_flutter: ^1.6.1
  # image_picker: ^1.0.4
  # path_provider: ^2.1.1
  # audioplayers: ^4.1.0
  # permission_handler: ^11.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
  #   - images/a_dot_ham.jpeg

 
