name: personal_injury_networking
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 2.0.1+26

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^4.0.3
  flutter_screenutil: ^5.6.1
  flutter_rating_stars: ^1.0.3+4
  page_transition: ^2.1.0
  stepper_page_view: ^0.0.2
  provider: ^6.0.5
  geolocator: ^9.0.2
  flutter_google_places: ^0.3.0
  cloud_firestore: ^4.11.0
  firebase_auth: ^4.11.1
  email_validator: ^2.1.17
  google_geocoding: ^0.2.0
  firebase_core: ^2.19.0
  google_maps_flutter: ^2.0.0
  intl: ^0.18.1
  image_picker: ^1.0.4
  firebase_storage: ^11.4.0
  flutter_spinkit: ^5.1.0
  http: ^0.13.5
  qr_flutter: ^4.0.0
  qr_code_scanner: ^1.0.1
  google_sign_in: ^6.1.5
  the_apple_sign_in: ^1.1.1
  sign_in_with_apple: ^5.0.0
  file_picker: ^6.1.1
  record: ^5.0.1
  audioplayers: ^5.2.0
  path_provider: ^2.1.1
  firebase_messaging: ^14.7.4
  overlay_support: ^2.1.0
  shared_preferences: ^2.2.2
  badges: ^3.1.2
  firebase_crashlytics: ^3.4.9
  url_launcher: ^6.1.12
  dropdown_button2: ^2.3.9
  mobkit_dashed_border: ^0.0.5
dev_dependencies:
  flutter_test:
    sdk: flutter
#comment
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
  #   - images/a_dot_ham.jpeg

 